apiVersion: v1
kind: Service
metadata:
  name: kustomize-guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-guestbook-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: docker.io/rahmansdocker/kubia:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
