apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-repo-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "argocd-repo-server"
  template:
    spec:
      containers:
      - name: pull
        image: ubuntu
        args:
        - /bin/sh
        - -c
        - apt-get update
        - apt-get install curl -y
        - mkdir base2
        - curl -o /base2/test.env https://raw.githubusercontent.com/rahman-saqib/kustomize-argocdimageupdater/main/test.env
        - ls base2
      nodeSelector:
          on-master: "true"
      restartPolicy: Never
  backoffLimit: 0
