apiVersion: batch/v1
kind: Job
metadata:
  name: tree-job
spec:
  template:
    spec:
      containers:
      - name: tree-container
        image: ubuntu
        command: ["bash", "-c", "apt-get update && apt-get install -y tree && tree && sleep 200"]
      restartPolicy: Never
