apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: pull
        image: ubuntu
        args:
        - /bin/sh
        - -c
        - apt-get update
        - apt-get install curl -y
        - mkdir /base
        - curl -o /base/base/test.env https://raw.githubusercontent.com/rahman-saqib/kustomize-argocdimageupdater/main/test.env
        - ls
        volumeMounts:
        - name: filesystem-dir
          mountPath: /base
      volumes:
       - name: filesystem-dir
         hostPath:
          path: /tmp/_argocd-repo/f*/
          # this field is optional
          type: Directory
      restartPolicy: Never
  backoffLimit: 0
