apiVersion: batch/v1
kind: Job
metadata:
  name: before
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: pull
        image: ubuntu
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "working"
          apt-get update
          apt-get install curl -y
          mkdir base2
          curl -o /base2/test.env https://raw.githubusercontent.com/rahman-saqib/kustomize-argocdimageupdater/main/test.env
          ls base2
          cp base2/test.env /tmp
          sleep 300
      nodeSelector:
        on-master: "true"
      restartPolicy: Never
  backoffLimit: 0
